export const AUTH_ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
};

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_ERROR = 'AUTH_REGISTER_ERROR';

export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
