export const MOVIES_API = {
  GET_LIST: '/list-movies',
  GET_MOVIE_INFO: '/movie',
  GET_COMMENTS_MOVIE: '/comments',
  POST_COMMENT: '/post-comment',
  SEARCH_MOVIE: '/search',
};

export const GET_LIST_MOVIE_REQUEST = 'GET_LIST_MOVIE_REQUEST';
export const GET_LIST_MOVIE_FAILED = 'GET_LIST_MOVIE_FAILED';

export const GET_MOVIE_INFO_REQUEST = 'GET_MOVIE_INFO_REQUEST';
export const GET_MOVIE_INFO_FAILED = 'GET_MOVIE_INFO_FAILED';

export const GET_COMMENT_REQUEST = 'GET_COMMENT_REQUEST';
export const GET_COMMENT_FAILED = 'GET_COMMENT_FAILED';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_FAILED = 'POST_COMMENT_FAILED';

export const SEARCH_MOVIE_REQUEST = 'SEARCH_MOVIE_REQUEST';
